name: Pylint

on: 
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  lint:
    name: pylint test on datatransformer code
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install faker
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        cd
        python -m pylint datatransformer
  
  unittest:
    name: Unit test on datatransformer code
    needs: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install faker
        pip install pytest
    - name: Unit testing the code
      run: |
        pytest --verbosity=2
